### ISSUE TITLE
Always keep /* @flow */ definitions at top of file

### ISSUE THREAD

**Issue by yodaiken** [4Catalyzer/import-sort-style-4catalyzer#4]

**Comment by jquense** [comment]
I tink you need to add a newline between the leading comment and the first import.

**Comment by yodaiken** [comment]
That does make it work. We may want to add a warning somewhere though if the newline isn't there in source file since currently the sorter just silently breaks.

**Comment by jquense** [comment]
Part of the issue is you can't necessarily know if the comment is supposed to move with the import, like: `eslint-disable-next-line ...` We could special flow comments but I don't actually think we have the hooks for that here.

Happy to add a note in the repo tho

**Comment by taion** [comment]
Can we hard-code support for block-type comments? We always write

```js
/* @flow */
/* eslint-disable rule-i-dont-like */

// eslint-disable-next-line
```

The ones at the top should never move. The ones at the bottom always move.

**Comment by jquense** [comment]
the problem is what importSort exposes api wise but we can ask for that.
